splash = false

wallpaper {
    monitor = eDP-1
    path = /home/dalton/.dotfiles/arch/modules/theme/wallpapers/catppuccin-mocha/escape_velocity.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-7
    path = /home/dalton/.dotfiles/arch/modules/theme/wallpapers/catppuccin-mocha/shaded_landscape.png
    fit_mode = cover
}
