[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "CaskaydiaCove Nerd Font"
size = 12

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"
