- 1.1.10
- _NAME: LIFT VERTICAL ERGONOMIC MOUSE
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer,
    adc_power_management]
  _battery: 4100
  _modelId: B03100000000
  _sensitive: {change-host: false, divert-keys: true, dpi: false, reprogrammable-keys: false}
  _serial: 75DE8EBA
  _unitId: 75DE8EBA
  _wpid: B031
  change-host: null
  divert-keys: {82: 0, 83: 1, 86: 1, 253: 0}
  dpi: 1700
  lowres-scroll-mode: false
  reprogrammable-keys: {82: 82, 83: 83, 86: 86, 253: 253}
